### ISSUE TITLE
Missing imports of the form import module.deprecated_func as yy

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch-labs/torchfix#45]
When deprecated functions are invoked using the format `import some_module.deprecated_func as yy` torchfix does not catch the failure

Specifically, [this line](https://github.com/pytorch-labs/torchfix/pull/44/files#diff-5848b24edbe42172ccbe6b63d6e1349fa28fe08bbfb8576f8e55d2422edec0f7R8) should  trigger a torchfix error, but it [does not](https://github.com/pytorch-labs/torchfix/pull/44/files#diff-4d742431f9f44a2894bf74b1e831326a6250b88e6eb0d47e559308006cca825aR1-R4):

```python
import torch.utils._pytree._register_pytree_node as yy
yy()
```

**Comment by kit1980** [comment]
Yeah, logic for `visit_Import`, similar to `visit_ImportFrom` needs to be added around here:
https://github.com/pytorch-labs/torchfix/blob/main/torchfix/visitors/deprecated_symbols/__init__.py#L60

Right not even just `import torch.utils._pytree._register_pytree_node` will not trigger the lint.

**Comment by kit1980** [comment]
Hm, you can not do `import torch.utils._pytree._register_pytree_node as yy `:

> ModuleNotFoundError: No module named 'torch.utils._pytree._register_pytree_node'; 'torch.utils._pytree' is not a package

**Comment by ZainRizvi** [comment]
Ah, right. Makes sense
