### ISSUE TITLE
Old deprecated import is not removed when direct replacement available

### ISSUE THREAD

**Issue by kit1980** [pytorch-labs/torchfix#50]
See this comment for an example https://github.com/pytorch-labs/torchfix/pull/44#discussion_r1575312520

**Comment by kit1980** [comment]
This is directly related to this TODO
https://github.com/pytorch-labs/torchfix/blob/main/torchfix/visitors/deprecated_symbols/__init__.py#L112

**Comment by huydhn** [comment]
Reassign this to @kit1980 after our chat.  My attempt to use https://libcst.readthedocs.io/en/latest/_modules/libcst/codemod/visitors/_remove_imports.html to remove the import in the same way as `AddImportsVisitor` is used, but it seems like a complex approach and also not keeping the import order.
